version: "3"
services:
  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=agencia.digitali.apps.com.pe,www.agencia.digitali.apps.com.pe
      - LETSENCRYPT_HOST=agencia.digitali.apps.com.pe,www.agencia.digitali.apps.com.pe
      - LETSENCRYPT_EMAIL=miguekos1233@gmail.com

  php:
    image: php:7-fpm
    volumes:
      - ./:/usr/share/nginx/html:ro

networks:
  default:
    external:
      name: nginx-proxy_default
