version: '3.0'

services:
  mysqlDigitali:
    container_name: mysql-Digitali
    environment:
      MYSQL_DATABASE: wordpress-Digitali
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
    image: mariadb:latest
    restart: unless-stopped
    volumes:
    - /usr/local/volumes/mysql-Digitali/:/var/lib/mysql:rw
  wordpressDigitali:
    container_name: wordpress-Digitali
    depends_on:
    - mysqlDigitali
    environment:
      LETSENCRYPT_EMAIL: miguekos1233@gmail.com
      LETSENCRYPT_HOST: agencia.digitali.apps.com.pe,www.agencia.digitali.apps.com.pe
      VIRTUAL_HOST: agencia.digitali.apps.com.pe,www.agencia.digitali.apps.com.pe
      WORDPRESS_DB_HOST: mysqlDigitali:3306
      WORDPRESS_DB_NAME: wordpress-Digitali
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_USER: root
      WORDPRESS_TABLE_PREFIX: wp_
    image: wordpress:latest
    logging:
      options:
        max-size: 200k
    restart: unless-stopped
    volumes:
    - /usr/local/volumes/wordpress-agenciadigital/wordpress-core:/var/www/html:rw
    - ./conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:rw

networks:
  default:
    external:
      name: nginx-proxy_default
